"""Generate the disk's CIE 1931 / Planck LUT. No runtime spectral integration."""
import csv
import hashlib
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "tools/data/CIE_xyz_1931_2deg.csv"
COUNT = 512
MIN_TEMP, MAX_TEMP = 500.0, 1000000.0


def spectrum_xyz(rows, temperature):
    xyz = [0.0, 0.0, 0.0]
    for index, (nm, *cmf) in enumerate(rows):
        wavelength = nm * 1e-9
        # Common 2hc^2 and wavelength interval cancel in relative radiance.
        radiance = wavelength ** -5 / math.expm1(0.014387768775039337 / (wavelength * temperature))
        weight = 0.5 if index in (0, len(rows) - 1) else 1.0
        for channel in range(3):
            xyz[channel] += cmf[channel] * radiance * weight
    return xyz


def main():
    raw = DATA.read_bytes()
    if hashlib.sha256(raw).hexdigest() != "fa663e3535a7e0763a745993a1f0a192eb0275ac46ad2d1befd7626841e713c1":
        raise ValueError("CIE source checksum mismatch")
    rows = [list(map(float, row)) for row in csv.reader(raw.decode().splitlines())]
    reference = spectrum_xyz(rows, 6500.0)[1]
    values = []
    for index in range(COUNT):
        temperature = MIN_TEMP * (MAX_TEMP / MIN_TEMP) ** (index / (COUNT - 1))
        x, y, z = spectrum_xyz(rows, temperature)
        # XYZ to linear sRGB (D65 primaries); preserve the emitter white point.
        rgb = (3.2404542*x - 1.5371385*y - 0.4985314*z,
               -0.9692660*x + 1.8760108*y + 0.0415560*z,
               0.0556434*x - 0.2040259*y + 1.0572252*z)
        rgb = [max(0.0, c / y) for c in rgb]
        luma = sum(c * w for c, w in zip(rgb, (0.2126729, 0.7151522, 0.0721750)))
        values.append(tuple(c / luma for c in rgb) + (math.log(y / reference),))
    lines = [
        "// Generated by tools/generate_blackbody.py; intentionally tracked runtime LUT.",
        "// CIE 2019, DOI:10.25039/CIE.DS.xvudnb9b. Data adaptation: CC BY-SA 4.0.",
        "// https://creativecommons.org/licenses/by-sa/4.0/ ; see tools/data/README.md.",
        "// RGB: unit luminance, linear sRGB. W: log luminance relative to 6500 K.",
        f"const vec4 BLACKBODY_LUT[{COUNT}] = vec4[](",
    ]
    lines += ["    vec4(" + ", ".join(f"{c:.9f}" for c in v) + ")" +
              ("," if i < COUNT - 1 else "") for i, v in enumerate(values)]
    lines += [");", "", "vec4 blackbody_sample(float temperature)", "{",
              f"    float index = log(clamp(temperature, {MIN_TEMP:.1f}, {MAX_TEMP:.1f}) / {MIN_TEMP:.1f}) * ({COUNT - 1:.1f} / log({MAX_TEMP / MIN_TEMP:.1f}));",
              f"    int lo = min(int(index), {COUNT - 2});",
              "    return mix(BLACKBODY_LUT[lo], BLACKBODY_LUT[lo + 1], index - float(lo));", "}", ""]
    target = ROOT / "shaders/blackhole/blackbody.glsl"
    target.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {COUNT} temperatures from {len(rows)} CIE samples: {target}")


if __name__ == "__main__":
    main()
